"""add_warehouse_quality_models

Revision ID: a6a4acf556a0
Revises: f5365f9f9e94
Create Date: 2026-06-05 19:59:15.374885+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a4acf556a0'
down_revision: Union[str, None] = 'f5365f9f9e94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
