"""expand_agro_weather_data_full

Revision ID: 148b449e65bb
Revises: c969bc85b7d8
Create Date: 2026-06-05 19:30:12.597174+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '148b449e65bb'
down_revision: Union[str, None] = 'c969bc85b7d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agro_weather_data', sa.Column('apparent_temp', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('dew_point', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('relative_humidity', sa.Integer(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('vapour_pressure_deficit', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('precipitation', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('rain', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('showers', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('snowfall', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('snow_depth', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('weather_code', sa.Integer(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('cloud_cover', sa.Integer(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('pressure_msl', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('surface_pressure', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('visibility', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('sunshine_duration', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('shortwave_radiation', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('direct_radiation', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('diffuse_radiation', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('is_day', sa.Integer(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('wind_speed', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('wind_direction', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('wind_gusts', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('soil_temp_0cm', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('soil_temp_6cm', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('soil_temp_18cm', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('soil_temp_54cm', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('soil_moisture_0_1cm', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('soil_moisture_1_3cm', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('soil_moisture_3_9cm', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('soil_moisture_9_27cm', sa.Float(), nullable=True))
    op.add_column('agro_weather_data', sa.Column('soil_moisture_27_81cm', sa.Float(), nullable=True))
    op.alter_column('agro_weather_data', 'warnings',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_column('agro_weather_data', 'soil_temp')
    op.drop_column('agro_weather_data', 'soil_moisture')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agro_weather_data', sa.Column('soil_moisture', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('agro_weather_data', sa.Column('soil_temp', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.alter_column('agro_weather_data', 'warnings',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('agro_weather_data', 'soil_moisture_27_81cm')
    op.drop_column('agro_weather_data', 'soil_moisture_9_27cm')
    op.drop_column('agro_weather_data', 'soil_moisture_3_9cm')
    op.drop_column('agro_weather_data', 'soil_moisture_1_3cm')
    op.drop_column('agro_weather_data', 'soil_moisture_0_1cm')
    op.drop_column('agro_weather_data', 'soil_temp_54cm')
    op.drop_column('agro_weather_data', 'soil_temp_18cm')
    op.drop_column('agro_weather_data', 'soil_temp_6cm')
    op.drop_column('agro_weather_data', 'soil_temp_0cm')
    op.drop_column('agro_weather_data', 'wind_gusts')
    op.drop_column('agro_weather_data', 'wind_direction')
    op.drop_column('agro_weather_data', 'wind_speed')
    op.drop_column('agro_weather_data', 'is_day')
    op.drop_column('agro_weather_data', 'diffuse_radiation')
    op.drop_column('agro_weather_data', 'direct_radiation')
    op.drop_column('agro_weather_data', 'shortwave_radiation')
    op.drop_column('agro_weather_data', 'sunshine_duration')
    op.drop_column('agro_weather_data', 'visibility')
    op.drop_column('agro_weather_data', 'surface_pressure')
    op.drop_column('agro_weather_data', 'pressure_msl')
    op.drop_column('agro_weather_data', 'cloud_cover')
    op.drop_column('agro_weather_data', 'weather_code')
    op.drop_column('agro_weather_data', 'snow_depth')
    op.drop_column('agro_weather_data', 'snowfall')
    op.drop_column('agro_weather_data', 'showers')
    op.drop_column('agro_weather_data', 'rain')
    op.drop_column('agro_weather_data', 'precipitation')
    op.drop_column('agro_weather_data', 'vapour_pressure_deficit')
    op.drop_column('agro_weather_data', 'relative_humidity')
    op.drop_column('agro_weather_data', 'dew_point')
    op.drop_column('agro_weather_data', 'apparent_temp')
    # ### end Alembic commands ###
